# Generated by Django 5.0.6 on 2026-07-28 20:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Helpdesk', '0002_customer_department_customer_position_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketcomment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tickethistory',
            options={},
        ),
        migrations.RenameField(
            model_name='ticketcomment',
            old_name='comment',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='ticketcomment',
            old_name='author',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='tickethistory',
            old_name='note',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='tickethistory',
            old_name='changed_by',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='maintenanceevent',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='maintenanceevent',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='supportagent',
            name='specialty',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='assigned_by',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='impact',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='urgency',
        ),
        migrations.AddField(
            model_name='customer',
            name='full_name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sla',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supportagent',
            name='speciality',
            field=models.CharField(choices=[('Redes', 'Redes'), ('Hardware', 'Hardware'), ('Software', 'Software'), ('Bases de datos', 'Bases de datos'), ('Servidores', 'Servidores'), ('Seguridad', 'Seguridad'), ('Otros', 'Otros')], default='Otros', max_length=50),
        ),
        migrations.AddField(
            model_name='ticket',
            name='code',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='company',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='department',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='position',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipment_type',
            field=models.CharField(choices=[('Laptop', 'Laptop'), ('Desktop', 'Desktop'), ('Servidor', 'Servidor'), ('Impresora', 'Impresora'), ('Router', 'Router'), ('Switch', 'Switch'), ('Otro', 'Otro')], default='Otro', max_length=50),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment', to='Helpdesk.customer'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[('Operativo', 'Operativo'), ('En reparación', 'En reparación'), ('Fuera de servicio', 'Fuera de servicio')], default='Operativo', max_length=20),
        ),
        migrations.AlterField(
            model_name='sla',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='supportagent',
            name='role',
            field=models.CharField(default='Analista', max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('Hardware', 'Hardware'), ('Software', 'Software'), ('Red', 'Red'), ('Internet', 'Internet'), ('Correo electrónico', 'Correo electrónico'), ('Servidores', 'Servidores'), ('Bases de datos', 'Bases de datos'), ('Seguridad', 'Seguridad'), ('Otros', 'Otros')], default='Otros', max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Abierto', 'Abierto'), ('Asignado', 'Asignado'), ('En proceso', 'En proceso'), ('Pendiente', 'Pendiente'), ('Resuelto', 'Resuelto'), ('Cerrado', 'Cerrado')], default='Abierto', max_length=20),
        ),
        migrations.AlterField(
            model_name='tickethistory',
            name='new_status',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='tickethistory',
            name='old_status',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
