# Generated by Django 5.0.6 on 2026-07-28 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Helpdesk', '0003_alter_ticketcomment_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['full_name'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ['name'], 'verbose_name': 'Equipo', 'verbose_name_plural': 'Equipos'},
        ),
        migrations.AlterModelOptions(
            name='maintenanceevent',
            options={'ordering': ['-start_time'], 'verbose_name': 'Evento de Mantenimiento', 'verbose_name_plural': 'Eventos de Mantenimiento'},
        ),
        migrations.AlterModelOptions(
            name='sla',
            options={'ordering': ['name'], 'verbose_name': 'SLA', 'verbose_name_plural': 'SLAs'},
        ),
        migrations.AlterModelOptions(
            name='supportagent',
            options={'ordering': ['user__first_name'], 'verbose_name': 'Agente', 'verbose_name_plural': 'Agentes'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-created_at'], 'verbose_name': 'Ticket', 'verbose_name_plural': 'Tickets'},
        ),
        migrations.AlterModelOptions(
            name='ticketcomment',
            options={'ordering': ['created_at'], 'verbose_name': 'Comentario', 'verbose_name_plural': 'Comentarios'},
        ),
        migrations.AlterModelOptions(
            name='tickethistory',
            options={'ordering': ['-created_at'], 'verbose_name': 'Historial de Ticket', 'verbose_name_plural': 'Historial de Tickets'},
        ),
        migrations.AddField(
            model_name='maintenanceevent',
            name='color',
            field=models.CharField(default='#0d6efd', max_length=20),
        ),
        migrations.AddField(
            model_name='maintenanceevent',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tickethistory',
            name='action',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='tickethistory',
            name='new_value',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='tickethistory',
            name='old_value',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='maintenanceevent',
            name='event_type',
            field=models.CharField(choices=[('Mantenimiento', 'Mantenimiento'), ('Interrupción', 'Interrupción'), ('Actualización', 'Actualización'), ('Otro', 'Otro')], default='Mantenimiento', max_length=20),
        ),
        migrations.AlterField(
            model_name='supportagent',
            name='role',
            field=models.CharField(choices=[('Analista', 'Analista'), ('Especialista', 'Especialista'), ('Supervisor', 'Supervisor')], default='Analista', max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Abierto', 'Abierto'), ('Asignado', 'Asignado'), ('En proceso', 'En proceso'), ('Pendiente', 'Pendiente'), ('Resuelto', 'Resuelto'), ('Validado', 'Validado'), ('Cerrado', 'Cerrado')], default='Abierto', max_length=20),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('entity', models.CharField(max_length=50)),
                ('entity_id', models.PositiveIntegerField(blank=True, null=True)),
                ('detail', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Auditoría',
                'verbose_name_plural': 'Logs de Auditoría',
                'ordering': ['-created_at'],
            },
        ),
    ]
