# Generated by Django 5.0.6 on 2026-07-29 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Helpdesk', '0004_alter_customer_options_alter_equipment_options_and_more'),
        ('Helpdesk', '0004_auditlog_ticket_validated_at_and_more'),
    ]

    operations = [
    ]
